
name: CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.2
        with:
          node-version: 14.x 

      #Instalar as dependencias
      - name: Install dependencies
        run: yarn
      #Executar a build
      - name: Run build
        run: yarn build
      #Copiar pasta dist pra dentro da digitalocean
      - name: Copy dist to Digital Ocean
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          port: ${{ secrets.SSH_PORT }}
          password: ${{ secrets.SSH_PASSWORD }}
          source: "dist"
          target: "test"
      
      #Substituir o codigo existente na pasta "dist" pelo novo codigo
      #Executar "yarn"
      #Executar as migrations
      #Restart no servidor nodejs
      
